/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.slf4j.LoggerFactory

object App {
  private val logger = LoggerFactory.getLogger(getClass)
  def main(args: Array[String]): Unit = {
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
